        resources:
          requests:
            cpu: 200m
          limits:
            cpu: 500m

kubectl port-forward svc/svc-nginx 8080:80

while sleep 0.01; do curl http://127.0.0.1:63845; done

kubectl autoscale deployment deploy-nginx --cpu-percent=15 --min=1 --max=3