apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: yeshwanthbheempad/hello-world:4.0
        name: hello-world
        env:
        - name: APP_NAME
          value: "kube-PORT"
        ports:
        - containerPort: 3000