apiVersion: v1
kind: Service
metadata:
  name: sample-service
spec:
  selector:
    app: sample-deploy
  ports:
    - protocol: TCP
      port: 80        # service port
      targetPort: 3000 # container port inside the pods
  type: LoadBalancer
