apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sample-deploy
  name: sample-svc
spec:
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3000
    nodePort: 30000
  selector:
    app: sample-deploy
  type: NodePort
