apiVersion: v1
kind: Pod
metadata:
  name: hello-app
  labels:
    app: deploy-nginx
spec:
  containers:
   - image: piyushsachdeva/my-private-repo:latest
     name: hello-app
     resources:
      requests:
        cpu: 200m
      limits:
        cpu: 500m
     ports:
     - containerPort: 3000
  imagePullSecrets:
    - name: docker-secret