apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-nginx
  name: deploy-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-nginx
    spec:
      hostNetwork: true
      containers:
      - image: piyushsachdeva/hello-app:4.0
        name: hello-app
        envFrom:
        - configMapRef:
            name: sample-cm

        ports:
        - containerPort: 3000

